# include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - lib/localization/intl/**

  language:
    strict-inference: true

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
