blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/discussions
    about: Please ask and answer questions here
