name: form_builder_extra_fields
description: Additional fields for Flutter Form Builder package
version: 7.0.0-alpha.1
homepage: https://github.com/danvick/flutter_form_builder

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.0.0-alpha.1
  flutter_chips_input: ^1.9.5
  flutter_colorpicker: ^0.4.0
  rating_bar: ^0.2.0
  dropdown_search: ^0.6.1
  signature: ^4.1.1
  flutter_touch_spin: ^2.0.0-nullsafety.1
  intl: ^0.17.0
  flutter_typeahead: ^3.1.3
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

